### PR TITLE
[1/12] Improves coverage for src/dom, issue #10

### PR DESCRIPTION
**Pull request by Cijin**
Tests updated for the following functions:
* `isDocumentReady`
* `isDocumentInteractive`
* `urlEncode`

This is PR 1/12, due to the number of lines to be covered.

### CODE REVIEW

**Comment by bluepnume** [comment]
Thanks for taking this up!

For the first two tests, I think Flow is already covering the type-correctness of the functions. Karma tests are more to test the soundness of the logic. Would you mind adding a few tests which cover both the `true` and `false` cases, so the tests give a good indication of whether the logic is correct?

To do this, it may be helpful to have the functions accept a custom document. e.g.

```javascript
export function isDocumentInteractive(doc? : Document = document) : boolean {
    return doc.body && doc.readyState === 'interactive';
}
```

Then in the tests you can pass in a mocked document, like:

```javascript
const result = isDocumentInteractive({ body: {}, readyState: 'interactive' })
```

Thanks again!

**Comment by Cijin** [comment]
@bluepnume That makes sense. I will update those two tests. :smile:

**Comment by songz** [comment]
@bluepnume 

is it a good idea to change function shape specifically for the sake of testing? I see a potential for future engineers to be misled thinking they have to pass in arguments when it seems like the function should be used without arguments.

```
export function isDocumentInteractive(doc? : Document = document) : boolean {
    return doc.body && doc.readyState === 'interactive';
}
```

Would it make sense to have a unit test suite (like `jest`) to be able to mock the globals instead? Speaking of mocking, perhaps @Cijin could mock `document` global before the test, and then reset it back after the test.

```
const oldState = document.readyState;
document.readyState = ....
...run test....
document.readyState = oldState
```

**Comment by bluepnume** [comment]
Yeah @songz I agree, I'd normally avoid changing function shape if the only reason for it is to make testing easier.

The main reason I suggested it here is, it does add some utility to these functions:

- Default to the current document
- Allow passing in a custom document (e.g. a document from a different iframe or popup window) if required

That's a pattern we follow pretty extensively over in https://github.com/krakenjs/cross-domain-utils with the `win` parameter -- for example: https://github.com/krakenjs/cross-domain-utils/blob/master/src/utils.js#L18 - given that these repos are quite often dealing with window and document objects that are !== the `window` or `document` globals.

That said, if mocking `document` works here (and sometimes it will not -- certain properties can not be overwritten), I'm totally open to that too, at least until we have a real-world use case where we need to pass in a custom `doc`.

> I see a potential for future engineers to be misled thinking they have to pass in arguments when it seems like the function should be used without arguments.

That's a fair point too, that said it should (hopefully) be obvious both from the optional flow type for the param: `doc?`, and from the defaulting to `= document`.

**Comment by Cijin** [comment]
@songz & @bluepnume 

Thank you for both your inputs. Made my job a lot easier. So taking in your suggestions, I decided to mock the `readyState` property. 

It seemed like a much better way to move forward than changing the source code.

Please feel free to suggest any changes or alternative solutions.

**Comment by bluepnume** [comment]
Woot, thank you! These tests are looking great :)

**Pull request merged**
