### PR TITLE
[3/12] test for src/dom. Issue#10 --> Checks waitForDocumentReady function

### PR DESCRIPTION
**Pull request by Cijin**
* The function returns a promise that resolves when the document.`readyState` is `complete | interactive`
* Only checked for delayed document readyState as normal conditions have been checked in previous tests

### CODE REVIEW

**Comment by Cijin** [comment]
* The function is `memoized`, so I had to bust the cache by passing it a parameter.
* Although it works now, the next function `waitForDocumentBody` uses  `waitForDocumentReady` inside. Since it is memoized, it returns the cached results from the previous call.
* Could I please ask for some suggestions on how to get around this?
* Is there a way to clear the cache?
* So far,  i've tried `memoize.clear()`, maybe I wasn't using it right. It din work.

@bluepnume

**Comment by bluepnume** [comment]
Strange. Where are you calling `memoize.clear()`? In a `beforeEach` block?

**Comment by Cijin** [comment]
I used it in the `beforeEach` hook, same error. 
The error says `Weakmap expects key`

**Comment by bluepnume** [comment]
Looks like you caught a nasty bug with `memoize.clear()`! I've fixed it in master branch, can you try rebasing with master and try again?

**Comment by Cijin** [comment]
Yes that fixed it.
The tests work now. :)

**Comment by bluepnume** [comment]
Awesome! Thanks again!

**Pull request merged**
