### PR TITLE
[Improvement]Move readyState mock function into setup.js and run it first (#10)

### PR DESCRIPTION
**Pull request by Cijin**
* On the test for dom.js to mock the `readyState`, a new property was defined with a getter and setter. 
* One possible problem for the future tests is that, it could lead to inconsistencies if any tests for readyState manipulation are added before the existing ones.
* How?: Any tests defined before the mock functions definition will not be able to set values of readyState as it is by default a readonly property.
* This could cause a nightmare for someone trying to figure out what's causing this in the future.

### CODE REVIEW

**Comment by bluepnume** [comment]
Thanks! Can you check on the merge conflicts for this one?

**Comment by Cijin** [comment]
Merge conflicts fixed, and changes committed. :smile:

**Comment by bluepnume** [comment]
Ah looks like some lint checks are still failing. Can you try running `npm run lint -- --fix`?

**Comment by Cijin** [comment]
Fixed :)

**Review by songz — APPROVED** [review]

**Comment by bluepnume** [comment]
Woot, thanks!

**Pull request merged**
