### PR TITLE
feature/asyncFlag

### PR DESCRIPTION
**Pull request by mnicpt**
- Adds async flag so we can false value for synchronous logging on unload of page to simulate `sendBeacon` functionality from `beaver-logger`.

### CODE REVIEW

**Comment by bluepnume** [comment]
We should avoid doing synchronous ajax calls on page unload. We tried this in the past -- it causes the entire page to stall on unload, for the duration of the logging call.

**Comment by bluepnume** [comment]
Doing sync ajax calls is also deprecated in most browsers.

**Comment by mnicpt** [comment]
> Doing sync ajax calls is also deprecated in most browsers.

The motivation came from `sendBeacon`.  How does that have 94% usage? https://caniuse.com/#search=sendBeacon Just compile usage?  Should we consider doing an async/await scenario here and then returning when the logging response returns?

**Comment by bluepnume** [comment]
Sure -- sorry I specifically meant ajax calls with XMLHttpRequest. If we want to upgrade beaver-logger to support sendBeacon, that's totally fine with me.

**Pull request closed without merging**
